#!/usr/bin/env python3
"""Reproduce the stipulated example and its exact include-ready PGFPlots source."""

from __future__ import annotations

import hashlib
import json
from fractions import Fraction
from pathlib import Path

ROOT = Path(__file__).resolve().parent


def main() -> None:
    input_path = ROOT / "decision-sufficiency.inputs.json"
    data = json.loads(input_path.read_text())
    q = lambda value: Fraction(str(value))
    actions = data["actions"]
    a0, a1 = (q(actions["A"][key]) for key in ("intercept", "slope"))
    b0, b1 = (q(actions["B"][key]) for key in ("intercept", "slope"))
    domain_lo, domain_hi = map(q, data["condition"]["domain"])
    assert a1 != b1
    crossing = (b0 - a0) / (a1 - b1)
    assert domain_lo < crossing < domain_hi
    assert a0 + a1 * crossing == b0 + b1 * crossing

    values = []
    interval_tex = []
    for item in data["compatible_sets"]:
        lo, hi = map(q, item["interval"])
        assert domain_lo <= lo < hi <= domain_hi
        differences = [a0 + a1 * x - b0 - b1 * x for x in (lo, hi)]
        result = "A" if max(differences) < 0 else "B" if min(differences) > 0 else "unresolved"
        values.append({"id": item["id"], "difference_at_endpoints": list(map(float, differences)), "preference": result})
        y = item["row"]
        middle = float((lo + hi) / 2)
        # All intervals use identical marks: colour does not encode confidence.
        interval_tex.extend([
            rf"\addplot[draw=ink, line width=1.1pt] coordinates {{({float(lo)},{y}) ({float(hi)},{y})}};",
            rf"\addplot[draw=ink, line width=0.6pt] coordinates {{({float(lo)},{y - 0.09}) ({float(lo)},{y + 0.09})}};",
            rf"\addplot[draw=ink, line width=0.6pt] coordinates {{({float(hi)},{y - 0.09}) ({float(hi)},{y + 0.09})}};",
            rf"\node[anchor=south, inner sep=0pt] at (axis cs:{middle},{y + 0.17}) {{{item['label']}}};",
        ])
    assert [item["preference"] for item in values] == ["unresolved", "A", "B"]
    result = {
        "input_sha256": hashlib.sha256(input_path.read_bytes()).hexdigest(),
        "crossing": float(crossing),
        "loss_at_crossing": float(a0 + a1 * crossing),
        "cases": values,
        "checks": "Exact rational arithmetic; crossing equality; endpoint comparison suffices because the loss difference is affine; every interval lies within the declared domain.",
    }
    (ROOT / "decision-sufficiency.values.json").write_text(json.dumps(result, indent=2) + "\n")
    source = r"""% Required packages: amsmath, pgfplots
% Required TikZ libraries: none
% Target width: 155 mm maximum
% Minimum text size: 9 pt
% Colour/greyscale intent: colour and greyscale, redundant line styles and direct labels
% Generated by calculate_sufficiency.py from decision-sufficiency.inputs.json.
% All values are illustrative; conditional intervals are not confidence intervals.
\begin{tikzpicture}[font=\fontsize{9}{11}\selectfont]
\definecolor{ink}{HTML}{25313D}
\definecolor{accent}{HTML}{126C8A}
\pgfplotsset{compat=1.18,
  decision axis/.style={
    width=60mm, height=48mm, scale only axis,
    xmin=0, xmax=1, xtick={0,0.5,1},
    axis lines=left, axis line style={line width=0.45pt, draw=ink},
    tick style={line width=0.45pt, draw=ink},
    tick align=outside, ticklabel style={font=\fontsize{9}{11}\selectfont},
    xlabel={$\theta$ (dimensionless)},
    xlabel style={font=\fontsize{9}{11}\selectfont},
    every axis plot/.append style={no marks},
    clip=false, enlargelimits=false}}
\begin{axis}[decision axis, name=losses, at={(0mm,0mm)}, anchor=south west,
  ymin=0, ymax=8.5, ytick={0,2,5,8},
  ylabel={Loss (arbitrary units)},
  ylabel style={font=\fontsize{9}{11}\selectfont},
  title={\textbf{a}\quad Loss under each action},
  title style={font=\fontsize{10}{12}\selectfont, at={(0,1.10)}, anchor=west}]
\addplot[draw=black!55, dashed, line width=0.45pt] coordinates {(0.5,0) (0.5,8.5)};
\addplot[draw=accent, line width=0.85pt] coordinates {__A_COORDS__};
\addplot[draw=ink, densely dashed, line width=0.85pt] coordinates {__B_COORDS__};
\node[anchor=south east, text=accent, inner sep=0pt] at (axis cs:0.98,8.02) {$A$};
\node[anchor=south east, text=ink, inner sep=0pt] at (axis cs:0.98,5.18) {$B$};
\end{axis}
\begin{axis}[decision axis, at={(75mm,0mm)}, anchor=south west,
  ymin=0.5, ymax=3.8, ytick=\empty, axis y line=none,
  title={\textbf{b}\quad Compatible conditions},
  title style={font=\fontsize{10}{12}\selectfont, at={(0,1.10)}, anchor=west}]
\addplot[draw=black!55, dashed, line width=0.45pt] coordinates {(0.5,0.5) (0.5,3.1)};
__INTERVALS__
\end{axis}
\end{tikzpicture}
"""
    coords = lambda c0, c1: f"({float(domain_lo)},{float(c0 + c1 * domain_lo)}) ({float(domain_hi)},{float(c0 + c1 * domain_hi)})"
    source = source.replace("__A_COORDS__", coords(a0, a1)).replace("__B_COORDS__", coords(b0, b1))
    source = source.replace("__INTERVALS__", "\n".join(interval_tex))
    (ROOT / "decision-sufficiency.tikz.tex").write_text(source)


if __name__ == "__main__":
    main()
